# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

baseurl: /stn
exclude: ['README.md', 'Gemfile']
permalink: pretty

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss

title:
  es: STN - Bienvenido
  en: STN - Welcome
email: your-email@domain.com
description:
  es: Una descripcion en español
  en: Some description in english
index:
  es: 
  en: welcome
github_username:  santuan

t:
  es:
    open-source:
      name: "Collecciones Open Source"
      url: "/codigo-abierto/"
  en:
    open-source:
      name: "Open Source Collecttion"
      url: "/open-source/"

